# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/bugdom_wasm/bugdom_wasm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/bugdom_wasm/bugdom_wasm/build-wasm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/bugdom_wasm/bugdom_wasm/build-wasm/CMakeFiles /home/runner/work/bugdom_wasm/bugdom_wasm/build-wasm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/bugdom_wasm/bugdom_wasm/build-wasm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/runner/work/bugdom_wasm/bugdom_wasm/build-wasm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bugdom

# Build rule for target.
Bugdom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bugdom
.PHONY : Bugdom

# fast build rule for target.
Bugdom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/build
.PHONY : Bugdom/fast

#=============================================================================
# Target rules for targets named SDL3-static

# Build rule for target.
SDL3-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3-static
.PHONY : SDL3-static

# fast build rule for target.
SDL3-static/fast:
	$(MAKE) $(MAKESILENT) -f extern/SDL/CMakeFiles/SDL3-static.dir/build.make extern/SDL/CMakeFiles/SDL3-static.dir/build
.PHONY : SDL3-static/fast

#=============================================================================
# Target rules for targets named SDL3_test

# Build rule for target.
SDL3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_test
.PHONY : SDL3_test

# fast build rule for target.
SDL3_test/fast:
	$(MAKE) $(MAKESILENT) -f extern/SDL/CMakeFiles/SDL3_test.dir/build.make extern/SDL/CMakeFiles/SDL3_test.dir/build
.PHONY : SDL3_test/fast

#=============================================================================
# Target rules for targets named Pomme

# Build rule for target.
Pomme: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pomme
.PHONY : Pomme

# fast build rule for target.
Pomme/fast:
	$(MAKE) $(MAKESILENT) -f extern/Pomme/CMakeFiles/Pomme.dir/build.make extern/Pomme/CMakeFiles/Pomme.dir/build
.PHONY : Pomme/fast

src/Boot.o: src/Boot.cpp.o
.PHONY : src/Boot.o

# target to build an object file
src/Boot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Boot.cpp.o
.PHONY : src/Boot.cpp.o

src/Boot.i: src/Boot.cpp.i
.PHONY : src/Boot.i

# target to preprocess a source file
src/Boot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Boot.cpp.i
.PHONY : src/Boot.cpp.i

src/Boot.s: src/Boot.cpp.s
.PHONY : src/Boot.s

# target to generate assembly for a file
src/Boot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Boot.cpp.s
.PHONY : src/Boot.cpp.s

src/Enemies/Enemy.o: src/Enemies/Enemy.c.o
.PHONY : src/Enemies/Enemy.o

# target to build an object file
src/Enemies/Enemy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy.c.o
.PHONY : src/Enemies/Enemy.c.o

src/Enemies/Enemy.i: src/Enemies/Enemy.c.i
.PHONY : src/Enemies/Enemy.i

# target to preprocess a source file
src/Enemies/Enemy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy.c.i
.PHONY : src/Enemies/Enemy.c.i

src/Enemies/Enemy.s: src/Enemies/Enemy.c.s
.PHONY : src/Enemies/Enemy.s

# target to generate assembly for a file
src/Enemies/Enemy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy.c.s
.PHONY : src/Enemies/Enemy.c.s

src/Enemies/Enemy_Ant.o: src/Enemies/Enemy_Ant.c.o
.PHONY : src/Enemies/Enemy_Ant.o

# target to build an object file
src/Enemies/Enemy_Ant.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Ant.c.o
.PHONY : src/Enemies/Enemy_Ant.c.o

src/Enemies/Enemy_Ant.i: src/Enemies/Enemy_Ant.c.i
.PHONY : src/Enemies/Enemy_Ant.i

# target to preprocess a source file
src/Enemies/Enemy_Ant.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Ant.c.i
.PHONY : src/Enemies/Enemy_Ant.c.i

src/Enemies/Enemy_Ant.s: src/Enemies/Enemy_Ant.c.s
.PHONY : src/Enemies/Enemy_Ant.s

# target to generate assembly for a file
src/Enemies/Enemy_Ant.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Ant.c.s
.PHONY : src/Enemies/Enemy_Ant.c.s

src/Enemies/Enemy_Bee_Flying.o: src/Enemies/Enemy_Bee_Flying.c.o
.PHONY : src/Enemies/Enemy_Bee_Flying.o

# target to build an object file
src/Enemies/Enemy_Bee_Flying.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Bee_Flying.c.o
.PHONY : src/Enemies/Enemy_Bee_Flying.c.o

src/Enemies/Enemy_Bee_Flying.i: src/Enemies/Enemy_Bee_Flying.c.i
.PHONY : src/Enemies/Enemy_Bee_Flying.i

# target to preprocess a source file
src/Enemies/Enemy_Bee_Flying.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Bee_Flying.c.i
.PHONY : src/Enemies/Enemy_Bee_Flying.c.i

src/Enemies/Enemy_Bee_Flying.s: src/Enemies/Enemy_Bee_Flying.c.s
.PHONY : src/Enemies/Enemy_Bee_Flying.s

# target to generate assembly for a file
src/Enemies/Enemy_Bee_Flying.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Bee_Flying.c.s
.PHONY : src/Enemies/Enemy_Bee_Flying.c.s

src/Enemies/Enemy_BoxerFly.o: src/Enemies/Enemy_BoxerFly.c.o
.PHONY : src/Enemies/Enemy_BoxerFly.o

# target to build an object file
src/Enemies/Enemy_BoxerFly.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_BoxerFly.c.o
.PHONY : src/Enemies/Enemy_BoxerFly.c.o

src/Enemies/Enemy_BoxerFly.i: src/Enemies/Enemy_BoxerFly.c.i
.PHONY : src/Enemies/Enemy_BoxerFly.i

# target to preprocess a source file
src/Enemies/Enemy_BoxerFly.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_BoxerFly.c.i
.PHONY : src/Enemies/Enemy_BoxerFly.c.i

src/Enemies/Enemy_BoxerFly.s: src/Enemies/Enemy_BoxerFly.c.s
.PHONY : src/Enemies/Enemy_BoxerFly.s

# target to generate assembly for a file
src/Enemies/Enemy_BoxerFly.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_BoxerFly.c.s
.PHONY : src/Enemies/Enemy_BoxerFly.c.s

src/Enemies/Enemy_Caterpiller.o: src/Enemies/Enemy_Caterpiller.c.o
.PHONY : src/Enemies/Enemy_Caterpiller.o

# target to build an object file
src/Enemies/Enemy_Caterpiller.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Caterpiller.c.o
.PHONY : src/Enemies/Enemy_Caterpiller.c.o

src/Enemies/Enemy_Caterpiller.i: src/Enemies/Enemy_Caterpiller.c.i
.PHONY : src/Enemies/Enemy_Caterpiller.i

# target to preprocess a source file
src/Enemies/Enemy_Caterpiller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Caterpiller.c.i
.PHONY : src/Enemies/Enemy_Caterpiller.c.i

src/Enemies/Enemy_Caterpiller.s: src/Enemies/Enemy_Caterpiller.c.s
.PHONY : src/Enemies/Enemy_Caterpiller.s

# target to generate assembly for a file
src/Enemies/Enemy_Caterpiller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Caterpiller.c.s
.PHONY : src/Enemies/Enemy_Caterpiller.c.s

src/Enemies/Enemy_FireAnt.o: src/Enemies/Enemy_FireAnt.c.o
.PHONY : src/Enemies/Enemy_FireAnt.o

# target to build an object file
src/Enemies/Enemy_FireAnt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_FireAnt.c.o
.PHONY : src/Enemies/Enemy_FireAnt.c.o

src/Enemies/Enemy_FireAnt.i: src/Enemies/Enemy_FireAnt.c.i
.PHONY : src/Enemies/Enemy_FireAnt.i

# target to preprocess a source file
src/Enemies/Enemy_FireAnt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_FireAnt.c.i
.PHONY : src/Enemies/Enemy_FireAnt.c.i

src/Enemies/Enemy_FireAnt.s: src/Enemies/Enemy_FireAnt.c.s
.PHONY : src/Enemies/Enemy_FireAnt.s

# target to generate assembly for a file
src/Enemies/Enemy_FireAnt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_FireAnt.c.s
.PHONY : src/Enemies/Enemy_FireAnt.c.s

src/Enemies/Enemy_FireFly.o: src/Enemies/Enemy_FireFly.c.o
.PHONY : src/Enemies/Enemy_FireFly.o

# target to build an object file
src/Enemies/Enemy_FireFly.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_FireFly.c.o
.PHONY : src/Enemies/Enemy_FireFly.c.o

src/Enemies/Enemy_FireFly.i: src/Enemies/Enemy_FireFly.c.i
.PHONY : src/Enemies/Enemy_FireFly.i

# target to preprocess a source file
src/Enemies/Enemy_FireFly.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_FireFly.c.i
.PHONY : src/Enemies/Enemy_FireFly.c.i

src/Enemies/Enemy_FireFly.s: src/Enemies/Enemy_FireFly.c.s
.PHONY : src/Enemies/Enemy_FireFly.s

# target to generate assembly for a file
src/Enemies/Enemy_FireFly.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_FireFly.c.s
.PHONY : src/Enemies/Enemy_FireFly.c.s

src/Enemies/Enemy_KingAnt.o: src/Enemies/Enemy_KingAnt.c.o
.PHONY : src/Enemies/Enemy_KingAnt.o

# target to build an object file
src/Enemies/Enemy_KingAnt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_KingAnt.c.o
.PHONY : src/Enemies/Enemy_KingAnt.c.o

src/Enemies/Enemy_KingAnt.i: src/Enemies/Enemy_KingAnt.c.i
.PHONY : src/Enemies/Enemy_KingAnt.i

# target to preprocess a source file
src/Enemies/Enemy_KingAnt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_KingAnt.c.i
.PHONY : src/Enemies/Enemy_KingAnt.c.i

src/Enemies/Enemy_KingAnt.s: src/Enemies/Enemy_KingAnt.c.s
.PHONY : src/Enemies/Enemy_KingAnt.s

# target to generate assembly for a file
src/Enemies/Enemy_KingAnt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_KingAnt.c.s
.PHONY : src/Enemies/Enemy_KingAnt.c.s

src/Enemies/Enemy_Larva.o: src/Enemies/Enemy_Larva.c.o
.PHONY : src/Enemies/Enemy_Larva.o

# target to build an object file
src/Enemies/Enemy_Larva.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Larva.c.o
.PHONY : src/Enemies/Enemy_Larva.c.o

src/Enemies/Enemy_Larva.i: src/Enemies/Enemy_Larva.c.i
.PHONY : src/Enemies/Enemy_Larva.i

# target to preprocess a source file
src/Enemies/Enemy_Larva.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Larva.c.i
.PHONY : src/Enemies/Enemy_Larva.c.i

src/Enemies/Enemy_Larva.s: src/Enemies/Enemy_Larva.c.s
.PHONY : src/Enemies/Enemy_Larva.s

# target to generate assembly for a file
src/Enemies/Enemy_Larva.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Larva.c.s
.PHONY : src/Enemies/Enemy_Larva.c.s

src/Enemies/Enemy_Mosquito.o: src/Enemies/Enemy_Mosquito.c.o
.PHONY : src/Enemies/Enemy_Mosquito.o

# target to build an object file
src/Enemies/Enemy_Mosquito.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Mosquito.c.o
.PHONY : src/Enemies/Enemy_Mosquito.c.o

src/Enemies/Enemy_Mosquito.i: src/Enemies/Enemy_Mosquito.c.i
.PHONY : src/Enemies/Enemy_Mosquito.i

# target to preprocess a source file
src/Enemies/Enemy_Mosquito.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Mosquito.c.i
.PHONY : src/Enemies/Enemy_Mosquito.c.i

src/Enemies/Enemy_Mosquito.s: src/Enemies/Enemy_Mosquito.c.s
.PHONY : src/Enemies/Enemy_Mosquito.s

# target to generate assembly for a file
src/Enemies/Enemy_Mosquito.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Mosquito.c.s
.PHONY : src/Enemies/Enemy_Mosquito.c.s

src/Enemies/Enemy_PondFish.o: src/Enemies/Enemy_PondFish.c.o
.PHONY : src/Enemies/Enemy_PondFish.o

# target to build an object file
src/Enemies/Enemy_PondFish.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_PondFish.c.o
.PHONY : src/Enemies/Enemy_PondFish.c.o

src/Enemies/Enemy_PondFish.i: src/Enemies/Enemy_PondFish.c.i
.PHONY : src/Enemies/Enemy_PondFish.i

# target to preprocess a source file
src/Enemies/Enemy_PondFish.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_PondFish.c.i
.PHONY : src/Enemies/Enemy_PondFish.c.i

src/Enemies/Enemy_PondFish.s: src/Enemies/Enemy_PondFish.c.s
.PHONY : src/Enemies/Enemy_PondFish.s

# target to generate assembly for a file
src/Enemies/Enemy_PondFish.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_PondFish.c.s
.PHONY : src/Enemies/Enemy_PondFish.c.s

src/Enemies/Enemy_QueenBee.o: src/Enemies/Enemy_QueenBee.c.o
.PHONY : src/Enemies/Enemy_QueenBee.o

# target to build an object file
src/Enemies/Enemy_QueenBee.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_QueenBee.c.o
.PHONY : src/Enemies/Enemy_QueenBee.c.o

src/Enemies/Enemy_QueenBee.i: src/Enemies/Enemy_QueenBee.c.i
.PHONY : src/Enemies/Enemy_QueenBee.i

# target to preprocess a source file
src/Enemies/Enemy_QueenBee.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_QueenBee.c.i
.PHONY : src/Enemies/Enemy_QueenBee.c.i

src/Enemies/Enemy_QueenBee.s: src/Enemies/Enemy_QueenBee.c.s
.PHONY : src/Enemies/Enemy_QueenBee.s

# target to generate assembly for a file
src/Enemies/Enemy_QueenBee.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_QueenBee.c.s
.PHONY : src/Enemies/Enemy_QueenBee.c.s

src/Enemies/Enemy_Roach.o: src/Enemies/Enemy_Roach.c.o
.PHONY : src/Enemies/Enemy_Roach.o

# target to build an object file
src/Enemies/Enemy_Roach.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Roach.c.o
.PHONY : src/Enemies/Enemy_Roach.c.o

src/Enemies/Enemy_Roach.i: src/Enemies/Enemy_Roach.c.i
.PHONY : src/Enemies/Enemy_Roach.i

# target to preprocess a source file
src/Enemies/Enemy_Roach.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Roach.c.i
.PHONY : src/Enemies/Enemy_Roach.c.i

src/Enemies/Enemy_Roach.s: src/Enemies/Enemy_Roach.c.s
.PHONY : src/Enemies/Enemy_Roach.s

# target to generate assembly for a file
src/Enemies/Enemy_Roach.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Roach.c.s
.PHONY : src/Enemies/Enemy_Roach.c.s

src/Enemies/Enemy_Skippy.o: src/Enemies/Enemy_Skippy.c.o
.PHONY : src/Enemies/Enemy_Skippy.o

# target to build an object file
src/Enemies/Enemy_Skippy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Skippy.c.o
.PHONY : src/Enemies/Enemy_Skippy.c.o

src/Enemies/Enemy_Skippy.i: src/Enemies/Enemy_Skippy.c.i
.PHONY : src/Enemies/Enemy_Skippy.i

# target to preprocess a source file
src/Enemies/Enemy_Skippy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Skippy.c.i
.PHONY : src/Enemies/Enemy_Skippy.c.i

src/Enemies/Enemy_Skippy.s: src/Enemies/Enemy_Skippy.c.s
.PHONY : src/Enemies/Enemy_Skippy.s

# target to generate assembly for a file
src/Enemies/Enemy_Skippy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Skippy.c.s
.PHONY : src/Enemies/Enemy_Skippy.c.s

src/Enemies/Enemy_Slug.o: src/Enemies/Enemy_Slug.c.o
.PHONY : src/Enemies/Enemy_Slug.o

# target to build an object file
src/Enemies/Enemy_Slug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Slug.c.o
.PHONY : src/Enemies/Enemy_Slug.c.o

src/Enemies/Enemy_Slug.i: src/Enemies/Enemy_Slug.c.i
.PHONY : src/Enemies/Enemy_Slug.i

# target to preprocess a source file
src/Enemies/Enemy_Slug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Slug.c.i
.PHONY : src/Enemies/Enemy_Slug.c.i

src/Enemies/Enemy_Slug.s: src/Enemies/Enemy_Slug.c.s
.PHONY : src/Enemies/Enemy_Slug.s

# target to generate assembly for a file
src/Enemies/Enemy_Slug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Slug.c.s
.PHONY : src/Enemies/Enemy_Slug.c.s

src/Enemies/Enemy_Spider.o: src/Enemies/Enemy_Spider.c.o
.PHONY : src/Enemies/Enemy_Spider.o

# target to build an object file
src/Enemies/Enemy_Spider.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Spider.c.o
.PHONY : src/Enemies/Enemy_Spider.c.o

src/Enemies/Enemy_Spider.i: src/Enemies/Enemy_Spider.c.i
.PHONY : src/Enemies/Enemy_Spider.i

# target to preprocess a source file
src/Enemies/Enemy_Spider.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Spider.c.i
.PHONY : src/Enemies/Enemy_Spider.c.i

src/Enemies/Enemy_Spider.s: src/Enemies/Enemy_Spider.c.s
.PHONY : src/Enemies/Enemy_Spider.s

# target to generate assembly for a file
src/Enemies/Enemy_Spider.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Spider.c.s
.PHONY : src/Enemies/Enemy_Spider.c.s

src/Enemies/Enemy_Tick.o: src/Enemies/Enemy_Tick.c.o
.PHONY : src/Enemies/Enemy_Tick.o

# target to build an object file
src/Enemies/Enemy_Tick.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Tick.c.o
.PHONY : src/Enemies/Enemy_Tick.c.o

src/Enemies/Enemy_Tick.i: src/Enemies/Enemy_Tick.c.i
.PHONY : src/Enemies/Enemy_Tick.i

# target to preprocess a source file
src/Enemies/Enemy_Tick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Tick.c.i
.PHONY : src/Enemies/Enemy_Tick.c.i

src/Enemies/Enemy_Tick.s: src/Enemies/Enemy_Tick.c.s
.PHONY : src/Enemies/Enemy_Tick.s

# target to generate assembly for a file
src/Enemies/Enemy_Tick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_Tick.c.s
.PHONY : src/Enemies/Enemy_Tick.c.s

src/Enemies/Enemy_WorkerBee.o: src/Enemies/Enemy_WorkerBee.c.o
.PHONY : src/Enemies/Enemy_WorkerBee.o

# target to build an object file
src/Enemies/Enemy_WorkerBee.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_WorkerBee.c.o
.PHONY : src/Enemies/Enemy_WorkerBee.c.o

src/Enemies/Enemy_WorkerBee.i: src/Enemies/Enemy_WorkerBee.c.i
.PHONY : src/Enemies/Enemy_WorkerBee.i

# target to preprocess a source file
src/Enemies/Enemy_WorkerBee.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_WorkerBee.c.i
.PHONY : src/Enemies/Enemy_WorkerBee.c.i

src/Enemies/Enemy_WorkerBee.s: src/Enemies/Enemy_WorkerBee.c.s
.PHONY : src/Enemies/Enemy_WorkerBee.s

# target to generate assembly for a file
src/Enemies/Enemy_WorkerBee.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Enemies/Enemy_WorkerBee.c.s
.PHONY : src/Enemies/Enemy_WorkerBee.c.s

src/Items/Effects.o: src/Items/Effects.c.o
.PHONY : src/Items/Effects.o

# target to build an object file
src/Items/Effects.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Effects.c.o
.PHONY : src/Items/Effects.c.o

src/Items/Effects.i: src/Items/Effects.c.i
.PHONY : src/Items/Effects.i

# target to preprocess a source file
src/Items/Effects.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Effects.c.i
.PHONY : src/Items/Effects.c.i

src/Items/Effects.s: src/Items/Effects.c.s
.PHONY : src/Items/Effects.s

# target to generate assembly for a file
src/Items/Effects.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Effects.c.s
.PHONY : src/Items/Effects.c.s

src/Items/Items.o: src/Items/Items.c.o
.PHONY : src/Items/Items.o

# target to build an object file
src/Items/Items.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Items.c.o
.PHONY : src/Items/Items.c.o

src/Items/Items.i: src/Items/Items.c.i
.PHONY : src/Items/Items.i

# target to preprocess a source file
src/Items/Items.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Items.c.i
.PHONY : src/Items/Items.c.i

src/Items/Items.s: src/Items/Items.c.s
.PHONY : src/Items/Items.s

# target to generate assembly for a file
src/Items/Items.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Items.c.s
.PHONY : src/Items/Items.c.s

src/Items/Items2.o: src/Items/Items2.c.o
.PHONY : src/Items/Items2.o

# target to build an object file
src/Items/Items2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Items2.c.o
.PHONY : src/Items/Items2.c.o

src/Items/Items2.i: src/Items/Items2.c.i
.PHONY : src/Items/Items2.i

# target to preprocess a source file
src/Items/Items2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Items2.c.i
.PHONY : src/Items/Items2.c.i

src/Items/Items2.s: src/Items/Items2.c.s
.PHONY : src/Items/Items2.s

# target to generate assembly for a file
src/Items/Items2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Items2.c.s
.PHONY : src/Items/Items2.c.s

src/Items/Liquids.o: src/Items/Liquids.c.o
.PHONY : src/Items/Liquids.o

# target to build an object file
src/Items/Liquids.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Liquids.c.o
.PHONY : src/Items/Liquids.c.o

src/Items/Liquids.i: src/Items/Liquids.c.i
.PHONY : src/Items/Liquids.i

# target to preprocess a source file
src/Items/Liquids.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Liquids.c.i
.PHONY : src/Items/Liquids.c.i

src/Items/Liquids.s: src/Items/Liquids.c.s
.PHONY : src/Items/Liquids.s

# target to generate assembly for a file
src/Items/Liquids.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Liquids.c.s
.PHONY : src/Items/Liquids.c.s

src/Items/Traps.o: src/Items/Traps.c.o
.PHONY : src/Items/Traps.o

# target to build an object file
src/Items/Traps.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Traps.c.o
.PHONY : src/Items/Traps.c.o

src/Items/Traps.i: src/Items/Traps.c.i
.PHONY : src/Items/Traps.i

# target to preprocess a source file
src/Items/Traps.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Traps.c.i
.PHONY : src/Items/Traps.c.i

src/Items/Traps.s: src/Items/Traps.c.s
.PHONY : src/Items/Traps.s

# target to generate assembly for a file
src/Items/Traps.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Traps.c.s
.PHONY : src/Items/Traps.c.s

src/Items/Triggers.o: src/Items/Triggers.c.o
.PHONY : src/Items/Triggers.o

# target to build an object file
src/Items/Triggers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Triggers.c.o
.PHONY : src/Items/Triggers.c.o

src/Items/Triggers.i: src/Items/Triggers.c.i
.PHONY : src/Items/Triggers.i

# target to preprocess a source file
src/Items/Triggers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Triggers.c.i
.PHONY : src/Items/Triggers.c.i

src/Items/Triggers.s: src/Items/Triggers.c.s
.PHONY : src/Items/Triggers.s

# target to generate assembly for a file
src/Items/Triggers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Triggers.c.s
.PHONY : src/Items/Triggers.c.s

src/Items/Triggers2.o: src/Items/Triggers2.c.o
.PHONY : src/Items/Triggers2.o

# target to build an object file
src/Items/Triggers2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Triggers2.c.o
.PHONY : src/Items/Triggers2.c.o

src/Items/Triggers2.i: src/Items/Triggers2.c.i
.PHONY : src/Items/Triggers2.i

# target to preprocess a source file
src/Items/Triggers2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Triggers2.c.i
.PHONY : src/Items/Triggers2.c.i

src/Items/Triggers2.s: src/Items/Triggers2.c.s
.PHONY : src/Items/Triggers2.s

# target to generate assembly for a file
src/Items/Triggers2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Items/Triggers2.c.s
.PHONY : src/Items/Triggers2.c.s

src/Player/MyGuy.o: src/Player/MyGuy.c.o
.PHONY : src/Player/MyGuy.o

# target to build an object file
src/Player/MyGuy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/MyGuy.c.o
.PHONY : src/Player/MyGuy.c.o

src/Player/MyGuy.i: src/Player/MyGuy.c.i
.PHONY : src/Player/MyGuy.i

# target to preprocess a source file
src/Player/MyGuy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/MyGuy.c.i
.PHONY : src/Player/MyGuy.c.i

src/Player/MyGuy.s: src/Player/MyGuy.c.s
.PHONY : src/Player/MyGuy.s

# target to generate assembly for a file
src/Player/MyGuy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/MyGuy.c.s
.PHONY : src/Player/MyGuy.c.s

src/Player/Player_Ball.o: src/Player/Player_Ball.c.o
.PHONY : src/Player/Player_Ball.o

# target to build an object file
src/Player/Player_Ball.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/Player_Ball.c.o
.PHONY : src/Player/Player_Ball.c.o

src/Player/Player_Ball.i: src/Player/Player_Ball.c.i
.PHONY : src/Player/Player_Ball.i

# target to preprocess a source file
src/Player/Player_Ball.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/Player_Ball.c.i
.PHONY : src/Player/Player_Ball.c.i

src/Player/Player_Ball.s: src/Player/Player_Ball.c.s
.PHONY : src/Player/Player_Ball.s

# target to generate assembly for a file
src/Player/Player_Ball.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/Player_Ball.c.s
.PHONY : src/Player/Player_Ball.c.s

src/Player/Player_Bug.o: src/Player/Player_Bug.c.o
.PHONY : src/Player/Player_Bug.o

# target to build an object file
src/Player/Player_Bug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/Player_Bug.c.o
.PHONY : src/Player/Player_Bug.c.o

src/Player/Player_Bug.i: src/Player/Player_Bug.c.i
.PHONY : src/Player/Player_Bug.i

# target to preprocess a source file
src/Player/Player_Bug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/Player_Bug.c.i
.PHONY : src/Player/Player_Bug.c.i

src/Player/Player_Bug.s: src/Player/Player_Bug.c.s
.PHONY : src/Player/Player_Bug.s

# target to generate assembly for a file
src/Player/Player_Bug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/Player_Bug.c.s
.PHONY : src/Player/Player_Bug.c.s

src/Player/Player_Control.o: src/Player/Player_Control.c.o
.PHONY : src/Player/Player_Control.o

# target to build an object file
src/Player/Player_Control.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/Player_Control.c.o
.PHONY : src/Player/Player_Control.c.o

src/Player/Player_Control.i: src/Player/Player_Control.c.i
.PHONY : src/Player/Player_Control.i

# target to preprocess a source file
src/Player/Player_Control.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/Player_Control.c.i
.PHONY : src/Player/Player_Control.c.i

src/Player/Player_Control.s: src/Player/Player_Control.c.s
.PHONY : src/Player/Player_Control.s

# target to generate assembly for a file
src/Player/Player_Control.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Player/Player_Control.c.s
.PHONY : src/Player/Player_Control.c.s

src/QD3D/3DMF.o: src/QD3D/3DMF.c.o
.PHONY : src/QD3D/3DMF.o

# target to build an object file
src/QD3D/3DMF.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/3DMF.c.o
.PHONY : src/QD3D/3DMF.c.o

src/QD3D/3DMF.i: src/QD3D/3DMF.c.i
.PHONY : src/QD3D/3DMF.i

# target to preprocess a source file
src/QD3D/3DMF.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/3DMF.c.i
.PHONY : src/QD3D/3DMF.c.i

src/QD3D/3DMF.s: src/QD3D/3DMF.c.s
.PHONY : src/QD3D/3DMF.s

# target to generate assembly for a file
src/QD3D/3DMF.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/3DMF.c.s
.PHONY : src/QD3D/3DMF.c.s

src/QD3D/3DMath.o: src/QD3D/3DMath.c.o
.PHONY : src/QD3D/3DMath.o

# target to build an object file
src/QD3D/3DMath.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/3DMath.c.o
.PHONY : src/QD3D/3DMath.c.o

src/QD3D/3DMath.i: src/QD3D/3DMath.c.i
.PHONY : src/QD3D/3DMath.i

# target to preprocess a source file
src/QD3D/3DMath.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/3DMath.c.i
.PHONY : src/QD3D/3DMath.c.i

src/QD3D/3DMath.s: src/QD3D/3DMath.c.s
.PHONY : src/QD3D/3DMath.s

# target to generate assembly for a file
src/QD3D/3DMath.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/3DMath.c.s
.PHONY : src/QD3D/3DMath.c.s

src/QD3D/Camera.o: src/QD3D/Camera.c.o
.PHONY : src/QD3D/Camera.o

# target to build an object file
src/QD3D/Camera.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/Camera.c.o
.PHONY : src/QD3D/Camera.c.o

src/QD3D/Camera.i: src/QD3D/Camera.c.i
.PHONY : src/QD3D/Camera.i

# target to preprocess a source file
src/QD3D/Camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/Camera.c.i
.PHONY : src/QD3D/Camera.c.i

src/QD3D/Camera.s: src/QD3D/Camera.c.s
.PHONY : src/QD3D/Camera.s

# target to generate assembly for a file
src/QD3D/Camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/Camera.c.s
.PHONY : src/QD3D/Camera.c.s

src/QD3D/EnvironmentMap.o: src/QD3D/EnvironmentMap.c.o
.PHONY : src/QD3D/EnvironmentMap.o

# target to build an object file
src/QD3D/EnvironmentMap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/EnvironmentMap.c.o
.PHONY : src/QD3D/EnvironmentMap.c.o

src/QD3D/EnvironmentMap.i: src/QD3D/EnvironmentMap.c.i
.PHONY : src/QD3D/EnvironmentMap.i

# target to preprocess a source file
src/QD3D/EnvironmentMap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/EnvironmentMap.c.i
.PHONY : src/QD3D/EnvironmentMap.c.i

src/QD3D/EnvironmentMap.s: src/QD3D/EnvironmentMap.c.s
.PHONY : src/QD3D/EnvironmentMap.s

# target to generate assembly for a file
src/QD3D/EnvironmentMap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/EnvironmentMap.c.s
.PHONY : src/QD3D/EnvironmentMap.c.s

src/QD3D/FrustumCulling.o: src/QD3D/FrustumCulling.c.o
.PHONY : src/QD3D/FrustumCulling.o

# target to build an object file
src/QD3D/FrustumCulling.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/FrustumCulling.c.o
.PHONY : src/QD3D/FrustumCulling.c.o

src/QD3D/FrustumCulling.i: src/QD3D/FrustumCulling.c.i
.PHONY : src/QD3D/FrustumCulling.i

# target to preprocess a source file
src/QD3D/FrustumCulling.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/FrustumCulling.c.i
.PHONY : src/QD3D/FrustumCulling.c.i

src/QD3D/FrustumCulling.s: src/QD3D/FrustumCulling.c.s
.PHONY : src/QD3D/FrustumCulling.s

# target to generate assembly for a file
src/QD3D/FrustumCulling.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/FrustumCulling.c.s
.PHONY : src/QD3D/FrustumCulling.c.s

src/QD3D/Pick.o: src/QD3D/Pick.c.o
.PHONY : src/QD3D/Pick.o

# target to build an object file
src/QD3D/Pick.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/Pick.c.o
.PHONY : src/QD3D/Pick.c.o

src/QD3D/Pick.i: src/QD3D/Pick.c.i
.PHONY : src/QD3D/Pick.i

# target to preprocess a source file
src/QD3D/Pick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/Pick.c.i
.PHONY : src/QD3D/Pick.c.i

src/QD3D/Pick.s: src/QD3D/Pick.c.s
.PHONY : src/QD3D/Pick.s

# target to generate assembly for a file
src/QD3D/Pick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/Pick.c.s
.PHONY : src/QD3D/Pick.c.s

src/QD3D/QD3D_Geometry.o: src/QD3D/QD3D_Geometry.c.o
.PHONY : src/QD3D/QD3D_Geometry.o

# target to build an object file
src/QD3D/QD3D_Geometry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/QD3D_Geometry.c.o
.PHONY : src/QD3D/QD3D_Geometry.c.o

src/QD3D/QD3D_Geometry.i: src/QD3D/QD3D_Geometry.c.i
.PHONY : src/QD3D/QD3D_Geometry.i

# target to preprocess a source file
src/QD3D/QD3D_Geometry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/QD3D_Geometry.c.i
.PHONY : src/QD3D/QD3D_Geometry.c.i

src/QD3D/QD3D_Geometry.s: src/QD3D/QD3D_Geometry.c.s
.PHONY : src/QD3D/QD3D_Geometry.s

# target to generate assembly for a file
src/QD3D/QD3D_Geometry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/QD3D_Geometry.c.s
.PHONY : src/QD3D/QD3D_Geometry.c.s

src/QD3D/QD3D_Support.o: src/QD3D/QD3D_Support.c.o
.PHONY : src/QD3D/QD3D_Support.o

# target to build an object file
src/QD3D/QD3D_Support.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/QD3D_Support.c.o
.PHONY : src/QD3D/QD3D_Support.c.o

src/QD3D/QD3D_Support.i: src/QD3D/QD3D_Support.c.i
.PHONY : src/QD3D/QD3D_Support.i

# target to preprocess a source file
src/QD3D/QD3D_Support.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/QD3D_Support.c.i
.PHONY : src/QD3D/QD3D_Support.c.i

src/QD3D/QD3D_Support.s: src/QD3D/QD3D_Support.c.s
.PHONY : src/QD3D/QD3D_Support.s

# target to generate assembly for a file
src/QD3D/QD3D_Support.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/QD3D_Support.c.s
.PHONY : src/QD3D/QD3D_Support.c.s

src/QD3D/Renderer.o: src/QD3D/Renderer.c.o
.PHONY : src/QD3D/Renderer.o

# target to build an object file
src/QD3D/Renderer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/Renderer.c.o
.PHONY : src/QD3D/Renderer.c.o

src/QD3D/Renderer.i: src/QD3D/Renderer.c.i
.PHONY : src/QD3D/Renderer.i

# target to preprocess a source file
src/QD3D/Renderer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/Renderer.c.i
.PHONY : src/QD3D/Renderer.c.i

src/QD3D/Renderer.s: src/QD3D/Renderer.c.s
.PHONY : src/QD3D/Renderer.s

# target to generate assembly for a file
src/QD3D/Renderer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/Renderer.c.s
.PHONY : src/QD3D/Renderer.c.s

src/QD3D/TextMesh.o: src/QD3D/TextMesh.c.o
.PHONY : src/QD3D/TextMesh.o

# target to build an object file
src/QD3D/TextMesh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/TextMesh.c.o
.PHONY : src/QD3D/TextMesh.c.o

src/QD3D/TextMesh.i: src/QD3D/TextMesh.c.i
.PHONY : src/QD3D/TextMesh.i

# target to preprocess a source file
src/QD3D/TextMesh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/TextMesh.c.i
.PHONY : src/QD3D/TextMesh.c.i

src/QD3D/TextMesh.s: src/QD3D/TextMesh.c.s
.PHONY : src/QD3D/TextMesh.s

# target to generate assembly for a file
src/QD3D/TextMesh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/TextMesh.c.s
.PHONY : src/QD3D/TextMesh.c.s

src/QD3D/gles3_rhi.o: src/QD3D/gles3_rhi.c.o
.PHONY : src/QD3D/gles3_rhi.o

# target to build an object file
src/QD3D/gles3_rhi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/gles3_rhi.c.o
.PHONY : src/QD3D/gles3_rhi.c.o

src/QD3D/gles3_rhi.i: src/QD3D/gles3_rhi.c.i
.PHONY : src/QD3D/gles3_rhi.i

# target to preprocess a source file
src/QD3D/gles3_rhi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/gles3_rhi.c.i
.PHONY : src/QD3D/gles3_rhi.c.i

src/QD3D/gles3_rhi.s: src/QD3D/gles3_rhi.c.s
.PHONY : src/QD3D/gles3_rhi.s

# target to generate assembly for a file
src/QD3D/gles3_rhi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/QD3D/gles3_rhi.c.s
.PHONY : src/QD3D/gles3_rhi.c.s

src/Ride/DragonFly.o: src/Ride/DragonFly.c.o
.PHONY : src/Ride/DragonFly.o

# target to build an object file
src/Ride/DragonFly.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Ride/DragonFly.c.o
.PHONY : src/Ride/DragonFly.c.o

src/Ride/DragonFly.i: src/Ride/DragonFly.c.i
.PHONY : src/Ride/DragonFly.i

# target to preprocess a source file
src/Ride/DragonFly.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Ride/DragonFly.c.i
.PHONY : src/Ride/DragonFly.c.i

src/Ride/DragonFly.s: src/Ride/DragonFly.c.s
.PHONY : src/Ride/DragonFly.s

# target to generate assembly for a file
src/Ride/DragonFly.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Ride/DragonFly.c.s
.PHONY : src/Ride/DragonFly.c.s

src/Ride/WaterBug.o: src/Ride/WaterBug.c.o
.PHONY : src/Ride/WaterBug.o

# target to build an object file
src/Ride/WaterBug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Ride/WaterBug.c.o
.PHONY : src/Ride/WaterBug.c.o

src/Ride/WaterBug.i: src/Ride/WaterBug.c.i
.PHONY : src/Ride/WaterBug.i

# target to preprocess a source file
src/Ride/WaterBug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Ride/WaterBug.c.i
.PHONY : src/Ride/WaterBug.c.i

src/Ride/WaterBug.s: src/Ride/WaterBug.c.s
.PHONY : src/Ride/WaterBug.s

# target to generate assembly for a file
src/Ride/WaterBug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Ride/WaterBug.c.s
.PHONY : src/Ride/WaterBug.c.s

src/Screens/AboutScreen.o: src/Screens/AboutScreen.c.o
.PHONY : src/Screens/AboutScreen.o

# target to build an object file
src/Screens/AboutScreen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/AboutScreen.c.o
.PHONY : src/Screens/AboutScreen.c.o

src/Screens/AboutScreen.i: src/Screens/AboutScreen.c.i
.PHONY : src/Screens/AboutScreen.i

# target to preprocess a source file
src/Screens/AboutScreen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/AboutScreen.c.i
.PHONY : src/Screens/AboutScreen.c.i

src/Screens/AboutScreen.s: src/Screens/AboutScreen.c.s
.PHONY : src/Screens/AboutScreen.s

# target to generate assembly for a file
src/Screens/AboutScreen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/AboutScreen.c.s
.PHONY : src/Screens/AboutScreen.c.s

src/Screens/BonusScreen.o: src/Screens/BonusScreen.c.o
.PHONY : src/Screens/BonusScreen.o

# target to build an object file
src/Screens/BonusScreen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/BonusScreen.c.o
.PHONY : src/Screens/BonusScreen.c.o

src/Screens/BonusScreen.i: src/Screens/BonusScreen.c.i
.PHONY : src/Screens/BonusScreen.i

# target to preprocess a source file
src/Screens/BonusScreen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/BonusScreen.c.i
.PHONY : src/Screens/BonusScreen.c.i

src/Screens/BonusScreen.s: src/Screens/BonusScreen.c.s
.PHONY : src/Screens/BonusScreen.s

# target to generate assembly for a file
src/Screens/BonusScreen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/BonusScreen.c.s
.PHONY : src/Screens/BonusScreen.c.s

src/Screens/FileSelect.o: src/Screens/FileSelect.c.o
.PHONY : src/Screens/FileSelect.o

# target to build an object file
src/Screens/FileSelect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/FileSelect.c.o
.PHONY : src/Screens/FileSelect.c.o

src/Screens/FileSelect.i: src/Screens/FileSelect.c.i
.PHONY : src/Screens/FileSelect.i

# target to preprocess a source file
src/Screens/FileSelect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/FileSelect.c.i
.PHONY : src/Screens/FileSelect.c.i

src/Screens/FileSelect.s: src/Screens/FileSelect.c.s
.PHONY : src/Screens/FileSelect.s

# target to generate assembly for a file
src/Screens/FileSelect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/FileSelect.c.s
.PHONY : src/Screens/FileSelect.c.s

src/Screens/HighScores.o: src/Screens/HighScores.c.o
.PHONY : src/Screens/HighScores.o

# target to build an object file
src/Screens/HighScores.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/HighScores.c.o
.PHONY : src/Screens/HighScores.c.o

src/Screens/HighScores.i: src/Screens/HighScores.c.i
.PHONY : src/Screens/HighScores.i

# target to preprocess a source file
src/Screens/HighScores.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/HighScores.c.i
.PHONY : src/Screens/HighScores.c.i

src/Screens/HighScores.s: src/Screens/HighScores.c.s
.PHONY : src/Screens/HighScores.s

# target to generate assembly for a file
src/Screens/HighScores.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/HighScores.c.s
.PHONY : src/Screens/HighScores.c.s

src/Screens/Infobar.o: src/Screens/Infobar.c.o
.PHONY : src/Screens/Infobar.o

# target to build an object file
src/Screens/Infobar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/Infobar.c.o
.PHONY : src/Screens/Infobar.c.o

src/Screens/Infobar.i: src/Screens/Infobar.c.i
.PHONY : src/Screens/Infobar.i

# target to preprocess a source file
src/Screens/Infobar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/Infobar.c.i
.PHONY : src/Screens/Infobar.c.i

src/Screens/Infobar.s: src/Screens/Infobar.c.s
.PHONY : src/Screens/Infobar.s

# target to generate assembly for a file
src/Screens/Infobar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/Infobar.c.s
.PHONY : src/Screens/Infobar.c.s

src/Screens/LevelIntro.o: src/Screens/LevelIntro.c.o
.PHONY : src/Screens/LevelIntro.o

# target to build an object file
src/Screens/LevelIntro.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/LevelIntro.c.o
.PHONY : src/Screens/LevelIntro.c.o

src/Screens/LevelIntro.i: src/Screens/LevelIntro.c.i
.PHONY : src/Screens/LevelIntro.i

# target to preprocess a source file
src/Screens/LevelIntro.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/LevelIntro.c.i
.PHONY : src/Screens/LevelIntro.c.i

src/Screens/LevelIntro.s: src/Screens/LevelIntro.c.s
.PHONY : src/Screens/LevelIntro.s

# target to generate assembly for a file
src/Screens/LevelIntro.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/LevelIntro.c.s
.PHONY : src/Screens/LevelIntro.c.s

src/Screens/LevelSelect.o: src/Screens/LevelSelect.c.o
.PHONY : src/Screens/LevelSelect.o

# target to build an object file
src/Screens/LevelSelect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/LevelSelect.c.o
.PHONY : src/Screens/LevelSelect.c.o

src/Screens/LevelSelect.i: src/Screens/LevelSelect.c.i
.PHONY : src/Screens/LevelSelect.i

# target to preprocess a source file
src/Screens/LevelSelect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/LevelSelect.c.i
.PHONY : src/Screens/LevelSelect.c.i

src/Screens/LevelSelect.s: src/Screens/LevelSelect.c.s
.PHONY : src/Screens/LevelSelect.s

# target to generate assembly for a file
src/Screens/LevelSelect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/LevelSelect.c.s
.PHONY : src/Screens/LevelSelect.c.s

src/Screens/MainMenu.o: src/Screens/MainMenu.c.o
.PHONY : src/Screens/MainMenu.o

# target to build an object file
src/Screens/MainMenu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/MainMenu.c.o
.PHONY : src/Screens/MainMenu.c.o

src/Screens/MainMenu.i: src/Screens/MainMenu.c.i
.PHONY : src/Screens/MainMenu.i

# target to preprocess a source file
src/Screens/MainMenu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/MainMenu.c.i
.PHONY : src/Screens/MainMenu.c.i

src/Screens/MainMenu.s: src/Screens/MainMenu.c.s
.PHONY : src/Screens/MainMenu.s

# target to generate assembly for a file
src/Screens/MainMenu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/MainMenu.c.s
.PHONY : src/Screens/MainMenu.c.s

src/Screens/MiscScreens.o: src/Screens/MiscScreens.c.o
.PHONY : src/Screens/MiscScreens.o

# target to build an object file
src/Screens/MiscScreens.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/MiscScreens.c.o
.PHONY : src/Screens/MiscScreens.c.o

src/Screens/MiscScreens.i: src/Screens/MiscScreens.c.i
.PHONY : src/Screens/MiscScreens.i

# target to preprocess a source file
src/Screens/MiscScreens.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/MiscScreens.c.i
.PHONY : src/Screens/MiscScreens.c.i

src/Screens/MiscScreens.s: src/Screens/MiscScreens.c.s
.PHONY : src/Screens/MiscScreens.s

# target to generate assembly for a file
src/Screens/MiscScreens.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/MiscScreens.c.s
.PHONY : src/Screens/MiscScreens.c.s

src/Screens/ModelDebug.o: src/Screens/ModelDebug.c.o
.PHONY : src/Screens/ModelDebug.o

# target to build an object file
src/Screens/ModelDebug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/ModelDebug.c.o
.PHONY : src/Screens/ModelDebug.c.o

src/Screens/ModelDebug.i: src/Screens/ModelDebug.c.i
.PHONY : src/Screens/ModelDebug.i

# target to preprocess a source file
src/Screens/ModelDebug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/ModelDebug.c.i
.PHONY : src/Screens/ModelDebug.c.i

src/Screens/ModelDebug.s: src/Screens/ModelDebug.c.s
.PHONY : src/Screens/ModelDebug.s

# target to generate assembly for a file
src/Screens/ModelDebug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/ModelDebug.c.s
.PHONY : src/Screens/ModelDebug.c.s

src/Screens/SettingsScreen.o: src/Screens/SettingsScreen.c.o
.PHONY : src/Screens/SettingsScreen.o

# target to build an object file
src/Screens/SettingsScreen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/SettingsScreen.c.o
.PHONY : src/Screens/SettingsScreen.c.o

src/Screens/SettingsScreen.i: src/Screens/SettingsScreen.c.i
.PHONY : src/Screens/SettingsScreen.i

# target to preprocess a source file
src/Screens/SettingsScreen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/SettingsScreen.c.i
.PHONY : src/Screens/SettingsScreen.c.i

src/Screens/SettingsScreen.s: src/Screens/SettingsScreen.c.s
.PHONY : src/Screens/SettingsScreen.s

# target to generate assembly for a file
src/Screens/SettingsScreen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/SettingsScreen.c.s
.PHONY : src/Screens/SettingsScreen.c.s

src/Screens/Title.o: src/Screens/Title.c.o
.PHONY : src/Screens/Title.o

# target to build an object file
src/Screens/Title.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/Title.c.o
.PHONY : src/Screens/Title.c.o

src/Screens/Title.i: src/Screens/Title.c.i
.PHONY : src/Screens/Title.i

# target to preprocess a source file
src/Screens/Title.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/Title.c.i
.PHONY : src/Screens/Title.c.i

src/Screens/Title.s: src/Screens/Title.c.s
.PHONY : src/Screens/Title.s

# target to generate assembly for a file
src/Screens/Title.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/Title.c.s
.PHONY : src/Screens/Title.c.s

src/Screens/UIRoutines.o: src/Screens/UIRoutines.c.o
.PHONY : src/Screens/UIRoutines.o

# target to build an object file
src/Screens/UIRoutines.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/UIRoutines.c.o
.PHONY : src/Screens/UIRoutines.c.o

src/Screens/UIRoutines.i: src/Screens/UIRoutines.c.i
.PHONY : src/Screens/UIRoutines.i

# target to preprocess a source file
src/Screens/UIRoutines.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/UIRoutines.c.i
.PHONY : src/Screens/UIRoutines.c.i

src/Screens/UIRoutines.s: src/Screens/UIRoutines.c.s
.PHONY : src/Screens/UIRoutines.s

# target to generate assembly for a file
src/Screens/UIRoutines.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/UIRoutines.c.s
.PHONY : src/Screens/UIRoutines.c.s

src/Screens/WinLose.o: src/Screens/WinLose.c.o
.PHONY : src/Screens/WinLose.o

# target to build an object file
src/Screens/WinLose.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/WinLose.c.o
.PHONY : src/Screens/WinLose.c.o

src/Screens/WinLose.i: src/Screens/WinLose.c.i
.PHONY : src/Screens/WinLose.i

# target to preprocess a source file
src/Screens/WinLose.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/WinLose.c.i
.PHONY : src/Screens/WinLose.c.i

src/Screens/WinLose.s: src/Screens/WinLose.c.s
.PHONY : src/Screens/WinLose.s

# target to generate assembly for a file
src/Screens/WinLose.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Screens/WinLose.c.s
.PHONY : src/Screens/WinLose.c.s

src/Skeleton/Bones.o: src/Skeleton/Bones.c.o
.PHONY : src/Skeleton/Bones.o

# target to build an object file
src/Skeleton/Bones.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/Bones.c.o
.PHONY : src/Skeleton/Bones.c.o

src/Skeleton/Bones.i: src/Skeleton/Bones.c.i
.PHONY : src/Skeleton/Bones.i

# target to preprocess a source file
src/Skeleton/Bones.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/Bones.c.i
.PHONY : src/Skeleton/Bones.c.i

src/Skeleton/Bones.s: src/Skeleton/Bones.c.s
.PHONY : src/Skeleton/Bones.s

# target to generate assembly for a file
src/Skeleton/Bones.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/Bones.c.s
.PHONY : src/Skeleton/Bones.c.s

src/Skeleton/SkeletonAnim.o: src/Skeleton/SkeletonAnim.c.o
.PHONY : src/Skeleton/SkeletonAnim.o

# target to build an object file
src/Skeleton/SkeletonAnim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/SkeletonAnim.c.o
.PHONY : src/Skeleton/SkeletonAnim.c.o

src/Skeleton/SkeletonAnim.i: src/Skeleton/SkeletonAnim.c.i
.PHONY : src/Skeleton/SkeletonAnim.i

# target to preprocess a source file
src/Skeleton/SkeletonAnim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/SkeletonAnim.c.i
.PHONY : src/Skeleton/SkeletonAnim.c.i

src/Skeleton/SkeletonAnim.s: src/Skeleton/SkeletonAnim.c.s
.PHONY : src/Skeleton/SkeletonAnim.s

# target to generate assembly for a file
src/Skeleton/SkeletonAnim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/SkeletonAnim.c.s
.PHONY : src/Skeleton/SkeletonAnim.c.s

src/Skeleton/SkeletonJoints.o: src/Skeleton/SkeletonJoints.c.o
.PHONY : src/Skeleton/SkeletonJoints.o

# target to build an object file
src/Skeleton/SkeletonJoints.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/SkeletonJoints.c.o
.PHONY : src/Skeleton/SkeletonJoints.c.o

src/Skeleton/SkeletonJoints.i: src/Skeleton/SkeletonJoints.c.i
.PHONY : src/Skeleton/SkeletonJoints.i

# target to preprocess a source file
src/Skeleton/SkeletonJoints.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/SkeletonJoints.c.i
.PHONY : src/Skeleton/SkeletonJoints.c.i

src/Skeleton/SkeletonJoints.s: src/Skeleton/SkeletonJoints.c.s
.PHONY : src/Skeleton/SkeletonJoints.s

# target to generate assembly for a file
src/Skeleton/SkeletonJoints.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/SkeletonJoints.c.s
.PHONY : src/Skeleton/SkeletonJoints.c.s

src/Skeleton/SkeletonObj.o: src/Skeleton/SkeletonObj.c.o
.PHONY : src/Skeleton/SkeletonObj.o

# target to build an object file
src/Skeleton/SkeletonObj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/SkeletonObj.c.o
.PHONY : src/Skeleton/SkeletonObj.c.o

src/Skeleton/SkeletonObj.i: src/Skeleton/SkeletonObj.c.i
.PHONY : src/Skeleton/SkeletonObj.i

# target to preprocess a source file
src/Skeleton/SkeletonObj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/SkeletonObj.c.i
.PHONY : src/Skeleton/SkeletonObj.c.i

src/Skeleton/SkeletonObj.s: src/Skeleton/SkeletonObj.c.s
.PHONY : src/Skeleton/SkeletonObj.s

# target to generate assembly for a file
src/Skeleton/SkeletonObj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Skeleton/SkeletonObj.c.s
.PHONY : src/Skeleton/SkeletonObj.c.s

src/System/Collision.o: src/System/Collision.c.o
.PHONY : src/System/Collision.o

# target to build an object file
src/System/Collision.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Collision.c.o
.PHONY : src/System/Collision.c.o

src/System/Collision.i: src/System/Collision.c.i
.PHONY : src/System/Collision.i

# target to preprocess a source file
src/System/Collision.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Collision.c.i
.PHONY : src/System/Collision.c.i

src/System/Collision.s: src/System/Collision.c.s
.PHONY : src/System/Collision.s

# target to generate assembly for a file
src/System/Collision.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Collision.c.s
.PHONY : src/System/Collision.c.s

src/System/File.o: src/System/File.c.o
.PHONY : src/System/File.o

# target to build an object file
src/System/File.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/File.c.o
.PHONY : src/System/File.c.o

src/System/File.i: src/System/File.c.i
.PHONY : src/System/File.i

# target to preprocess a source file
src/System/File.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/File.c.i
.PHONY : src/System/File.c.i

src/System/File.s: src/System/File.c.s
.PHONY : src/System/File.s

# target to generate assembly for a file
src/System/File.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/File.c.s
.PHONY : src/System/File.c.s

src/System/Input.o: src/System/Input.c.o
.PHONY : src/System/Input.o

# target to build an object file
src/System/Input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Input.c.o
.PHONY : src/System/Input.c.o

src/System/Input.i: src/System/Input.c.i
.PHONY : src/System/Input.i

# target to preprocess a source file
src/System/Input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Input.c.i
.PHONY : src/System/Input.c.i

src/System/Input.s: src/System/Input.c.s
.PHONY : src/System/Input.s

# target to generate assembly for a file
src/System/Input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Input.c.s
.PHONY : src/System/Input.c.s

src/System/InputMacLinearMouse.o: src/System/InputMacLinearMouse.c.o
.PHONY : src/System/InputMacLinearMouse.o

# target to build an object file
src/System/InputMacLinearMouse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/InputMacLinearMouse.c.o
.PHONY : src/System/InputMacLinearMouse.c.o

src/System/InputMacLinearMouse.i: src/System/InputMacLinearMouse.c.i
.PHONY : src/System/InputMacLinearMouse.i

# target to preprocess a source file
src/System/InputMacLinearMouse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/InputMacLinearMouse.c.i
.PHONY : src/System/InputMacLinearMouse.c.i

src/System/InputMacLinearMouse.s: src/System/InputMacLinearMouse.c.s
.PHONY : src/System/InputMacLinearMouse.s

# target to generate assembly for a file
src/System/InputMacLinearMouse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/InputMacLinearMouse.c.s
.PHONY : src/System/InputMacLinearMouse.c.s

src/System/Main.o: src/System/Main.c.o
.PHONY : src/System/Main.o

# target to build an object file
src/System/Main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Main.c.o
.PHONY : src/System/Main.c.o

src/System/Main.i: src/System/Main.c.i
.PHONY : src/System/Main.i

# target to preprocess a source file
src/System/Main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Main.c.i
.PHONY : src/System/Main.c.i

src/System/Main.s: src/System/Main.c.s
.PHONY : src/System/Main.s

# target to generate assembly for a file
src/System/Main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Main.c.s
.PHONY : src/System/Main.c.s

src/System/Misc.o: src/System/Misc.c.o
.PHONY : src/System/Misc.o

# target to build an object file
src/System/Misc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Misc.c.o
.PHONY : src/System/Misc.c.o

src/System/Misc.i: src/System/Misc.c.i
.PHONY : src/System/Misc.i

# target to preprocess a source file
src/System/Misc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Misc.c.i
.PHONY : src/System/Misc.c.i

src/System/Misc.s: src/System/Misc.c.s
.PHONY : src/System/Misc.s

# target to generate assembly for a file
src/System/Misc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Misc.c.s
.PHONY : src/System/Misc.c.s

src/System/MouseSmoothing.o: src/System/MouseSmoothing.c.o
.PHONY : src/System/MouseSmoothing.o

# target to build an object file
src/System/MouseSmoothing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/MouseSmoothing.c.o
.PHONY : src/System/MouseSmoothing.c.o

src/System/MouseSmoothing.i: src/System/MouseSmoothing.c.i
.PHONY : src/System/MouseSmoothing.i

# target to preprocess a source file
src/System/MouseSmoothing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/MouseSmoothing.c.i
.PHONY : src/System/MouseSmoothing.c.i

src/System/MouseSmoothing.s: src/System/MouseSmoothing.c.s
.PHONY : src/System/MouseSmoothing.s

# target to generate assembly for a file
src/System/MouseSmoothing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/MouseSmoothing.c.s
.PHONY : src/System/MouseSmoothing.c.s

src/System/Objects.o: src/System/Objects.c.o
.PHONY : src/System/Objects.o

# target to build an object file
src/System/Objects.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Objects.c.o
.PHONY : src/System/Objects.c.o

src/System/Objects.i: src/System/Objects.c.i
.PHONY : src/System/Objects.i

# target to preprocess a source file
src/System/Objects.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Objects.c.i
.PHONY : src/System/Objects.c.i

src/System/Objects.s: src/System/Objects.c.s
.PHONY : src/System/Objects.s

# target to generate assembly for a file
src/System/Objects.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Objects.c.s
.PHONY : src/System/Objects.c.s

src/System/Objects2.o: src/System/Objects2.c.o
.PHONY : src/System/Objects2.o

# target to build an object file
src/System/Objects2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Objects2.c.o
.PHONY : src/System/Objects2.c.o

src/System/Objects2.i: src/System/Objects2.c.i
.PHONY : src/System/Objects2.i

# target to preprocess a source file
src/System/Objects2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Objects2.c.i
.PHONY : src/System/Objects2.c.i

src/System/Objects2.s: src/System/Objects2.c.s
.PHONY : src/System/Objects2.s

# target to generate assembly for a file
src/System/Objects2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Objects2.c.s
.PHONY : src/System/Objects2.c.s

src/System/Pool.o: src/System/Pool.c.o
.PHONY : src/System/Pool.o

# target to build an object file
src/System/Pool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Pool.c.o
.PHONY : src/System/Pool.c.o

src/System/Pool.i: src/System/Pool.c.i
.PHONY : src/System/Pool.i

# target to preprocess a source file
src/System/Pool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Pool.c.i
.PHONY : src/System/Pool.c.i

src/System/Pool.s: src/System/Pool.c.s
.PHONY : src/System/Pool.s

# target to generate assembly for a file
src/System/Pool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Pool.c.s
.PHONY : src/System/Pool.c.s

src/System/SDLMaintenance.o: src/System/SDLMaintenance.c.o
.PHONY : src/System/SDLMaintenance.o

# target to build an object file
src/System/SDLMaintenance.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/SDLMaintenance.c.o
.PHONY : src/System/SDLMaintenance.c.o

src/System/SDLMaintenance.i: src/System/SDLMaintenance.c.i
.PHONY : src/System/SDLMaintenance.i

# target to preprocess a source file
src/System/SDLMaintenance.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/SDLMaintenance.c.i
.PHONY : src/System/SDLMaintenance.c.i

src/System/SDLMaintenance.s: src/System/SDLMaintenance.c.s
.PHONY : src/System/SDLMaintenance.s

# target to generate assembly for a file
src/System/SDLMaintenance.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/SDLMaintenance.c.s
.PHONY : src/System/SDLMaintenance.c.s

src/System/Sound.o: src/System/Sound.c.o
.PHONY : src/System/Sound.o

# target to build an object file
src/System/Sound.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Sound.c.o
.PHONY : src/System/Sound.c.o

src/System/Sound.i: src/System/Sound.c.i
.PHONY : src/System/Sound.i

# target to preprocess a source file
src/System/Sound.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Sound.c.i
.PHONY : src/System/Sound.c.i

src/System/Sound.s: src/System/Sound.c.s
.PHONY : src/System/Sound.s

# target to generate assembly for a file
src/System/Sound.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Sound.c.s
.PHONY : src/System/Sound.c.s

src/System/TGA.o: src/System/TGA.c.o
.PHONY : src/System/TGA.o

# target to build an object file
src/System/TGA.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/TGA.c.o
.PHONY : src/System/TGA.c.o

src/System/TGA.i: src/System/TGA.c.i
.PHONY : src/System/TGA.i

# target to preprocess a source file
src/System/TGA.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/TGA.c.i
.PHONY : src/System/TGA.c.i

src/System/TGA.s: src/System/TGA.c.s
.PHONY : src/System/TGA.s

# target to generate assembly for a file
src/System/TGA.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/TGA.c.s
.PHONY : src/System/TGA.c.s

src/System/Tween.o: src/System/Tween.c.o
.PHONY : src/System/Tween.o

# target to build an object file
src/System/Tween.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Tween.c.o
.PHONY : src/System/Tween.c.o

src/System/Tween.i: src/System/Tween.c.i
.PHONY : src/System/Tween.i

# target to preprocess a source file
src/System/Tween.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Tween.c.i
.PHONY : src/System/Tween.c.i

src/System/Tween.s: src/System/Tween.c.s
.PHONY : src/System/Tween.s

# target to generate assembly for a file
src/System/Tween.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Tween.c.s
.PHONY : src/System/Tween.c.s

src/System/Window.o: src/System/Window.c.o
.PHONY : src/System/Window.o

# target to build an object file
src/System/Window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Window.c.o
.PHONY : src/System/Window.c.o

src/System/Window.i: src/System/Window.c.i
.PHONY : src/System/Window.i

# target to preprocess a source file
src/System/Window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Window.c.i
.PHONY : src/System/Window.c.i

src/System/Window.s: src/System/Window.c.s
.PHONY : src/System/Window.s

# target to generate assembly for a file
src/System/Window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/System/Window.c.s
.PHONY : src/System/Window.c.s

src/Terrain/Fences.o: src/Terrain/Fences.c.o
.PHONY : src/Terrain/Fences.o

# target to build an object file
src/Terrain/Fences.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/Fences.c.o
.PHONY : src/Terrain/Fences.c.o

src/Terrain/Fences.i: src/Terrain/Fences.c.i
.PHONY : src/Terrain/Fences.i

# target to preprocess a source file
src/Terrain/Fences.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/Fences.c.i
.PHONY : src/Terrain/Fences.c.i

src/Terrain/Fences.s: src/Terrain/Fences.c.s
.PHONY : src/Terrain/Fences.s

# target to generate assembly for a file
src/Terrain/Fences.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/Fences.c.s
.PHONY : src/Terrain/Fences.c.s

src/Terrain/SplineItems.o: src/Terrain/SplineItems.c.o
.PHONY : src/Terrain/SplineItems.o

# target to build an object file
src/Terrain/SplineItems.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/SplineItems.c.o
.PHONY : src/Terrain/SplineItems.c.o

src/Terrain/SplineItems.i: src/Terrain/SplineItems.c.i
.PHONY : src/Terrain/SplineItems.i

# target to preprocess a source file
src/Terrain/SplineItems.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/SplineItems.c.i
.PHONY : src/Terrain/SplineItems.c.i

src/Terrain/SplineItems.s: src/Terrain/SplineItems.c.s
.PHONY : src/Terrain/SplineItems.s

# target to generate assembly for a file
src/Terrain/SplineItems.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/SplineItems.c.s
.PHONY : src/Terrain/SplineItems.c.s

src/Terrain/Terrain.o: src/Terrain/Terrain.c.o
.PHONY : src/Terrain/Terrain.o

# target to build an object file
src/Terrain/Terrain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/Terrain.c.o
.PHONY : src/Terrain/Terrain.c.o

src/Terrain/Terrain.i: src/Terrain/Terrain.c.i
.PHONY : src/Terrain/Terrain.i

# target to preprocess a source file
src/Terrain/Terrain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/Terrain.c.i
.PHONY : src/Terrain/Terrain.c.i

src/Terrain/Terrain.s: src/Terrain/Terrain.c.s
.PHONY : src/Terrain/Terrain.s

# target to generate assembly for a file
src/Terrain/Terrain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/Terrain.c.s
.PHONY : src/Terrain/Terrain.c.s

src/Terrain/Terrain2.o: src/Terrain/Terrain2.c.o
.PHONY : src/Terrain/Terrain2.o

# target to build an object file
src/Terrain/Terrain2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/Terrain2.c.o
.PHONY : src/Terrain/Terrain2.c.o

src/Terrain/Terrain2.i: src/Terrain/Terrain2.c.i
.PHONY : src/Terrain/Terrain2.i

# target to preprocess a source file
src/Terrain/Terrain2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/Terrain2.c.i
.PHONY : src/Terrain/Terrain2.c.i

src/Terrain/Terrain2.s: src/Terrain/Terrain2.c.s
.PHONY : src/Terrain/Terrain2.s

# target to generate assembly for a file
src/Terrain/Terrain2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bugdom.dir/build.make CMakeFiles/Bugdom.dir/src/Terrain/Terrain2.c.s
.PHONY : src/Terrain/Terrain2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Bugdom"
	@echo "... Pomme"
	@echo "... SDL3-static"
	@echo "... SDL3_test"
	@echo "... src/Boot.o"
	@echo "... src/Boot.i"
	@echo "... src/Boot.s"
	@echo "... src/Enemies/Enemy.o"
	@echo "... src/Enemies/Enemy.i"
	@echo "... src/Enemies/Enemy.s"
	@echo "... src/Enemies/Enemy_Ant.o"
	@echo "... src/Enemies/Enemy_Ant.i"
	@echo "... src/Enemies/Enemy_Ant.s"
	@echo "... src/Enemies/Enemy_Bee_Flying.o"
	@echo "... src/Enemies/Enemy_Bee_Flying.i"
	@echo "... src/Enemies/Enemy_Bee_Flying.s"
	@echo "... src/Enemies/Enemy_BoxerFly.o"
	@echo "... src/Enemies/Enemy_BoxerFly.i"
	@echo "... src/Enemies/Enemy_BoxerFly.s"
	@echo "... src/Enemies/Enemy_Caterpiller.o"
	@echo "... src/Enemies/Enemy_Caterpiller.i"
	@echo "... src/Enemies/Enemy_Caterpiller.s"
	@echo "... src/Enemies/Enemy_FireAnt.o"
	@echo "... src/Enemies/Enemy_FireAnt.i"
	@echo "... src/Enemies/Enemy_FireAnt.s"
	@echo "... src/Enemies/Enemy_FireFly.o"
	@echo "... src/Enemies/Enemy_FireFly.i"
	@echo "... src/Enemies/Enemy_FireFly.s"
	@echo "... src/Enemies/Enemy_KingAnt.o"
	@echo "... src/Enemies/Enemy_KingAnt.i"
	@echo "... src/Enemies/Enemy_KingAnt.s"
	@echo "... src/Enemies/Enemy_Larva.o"
	@echo "... src/Enemies/Enemy_Larva.i"
	@echo "... src/Enemies/Enemy_Larva.s"
	@echo "... src/Enemies/Enemy_Mosquito.o"
	@echo "... src/Enemies/Enemy_Mosquito.i"
	@echo "... src/Enemies/Enemy_Mosquito.s"
	@echo "... src/Enemies/Enemy_PondFish.o"
	@echo "... src/Enemies/Enemy_PondFish.i"
	@echo "... src/Enemies/Enemy_PondFish.s"
	@echo "... src/Enemies/Enemy_QueenBee.o"
	@echo "... src/Enemies/Enemy_QueenBee.i"
	@echo "... src/Enemies/Enemy_QueenBee.s"
	@echo "... src/Enemies/Enemy_Roach.o"
	@echo "... src/Enemies/Enemy_Roach.i"
	@echo "... src/Enemies/Enemy_Roach.s"
	@echo "... src/Enemies/Enemy_Skippy.o"
	@echo "... src/Enemies/Enemy_Skippy.i"
	@echo "... src/Enemies/Enemy_Skippy.s"
	@echo "... src/Enemies/Enemy_Slug.o"
	@echo "... src/Enemies/Enemy_Slug.i"
	@echo "... src/Enemies/Enemy_Slug.s"
	@echo "... src/Enemies/Enemy_Spider.o"
	@echo "... src/Enemies/Enemy_Spider.i"
	@echo "... src/Enemies/Enemy_Spider.s"
	@echo "... src/Enemies/Enemy_Tick.o"
	@echo "... src/Enemies/Enemy_Tick.i"
	@echo "... src/Enemies/Enemy_Tick.s"
	@echo "... src/Enemies/Enemy_WorkerBee.o"
	@echo "... src/Enemies/Enemy_WorkerBee.i"
	@echo "... src/Enemies/Enemy_WorkerBee.s"
	@echo "... src/Items/Effects.o"
	@echo "... src/Items/Effects.i"
	@echo "... src/Items/Effects.s"
	@echo "... src/Items/Items.o"
	@echo "... src/Items/Items.i"
	@echo "... src/Items/Items.s"
	@echo "... src/Items/Items2.o"
	@echo "... src/Items/Items2.i"
	@echo "... src/Items/Items2.s"
	@echo "... src/Items/Liquids.o"
	@echo "... src/Items/Liquids.i"
	@echo "... src/Items/Liquids.s"
	@echo "... src/Items/Traps.o"
	@echo "... src/Items/Traps.i"
	@echo "... src/Items/Traps.s"
	@echo "... src/Items/Triggers.o"
	@echo "... src/Items/Triggers.i"
	@echo "... src/Items/Triggers.s"
	@echo "... src/Items/Triggers2.o"
	@echo "... src/Items/Triggers2.i"
	@echo "... src/Items/Triggers2.s"
	@echo "... src/Player/MyGuy.o"
	@echo "... src/Player/MyGuy.i"
	@echo "... src/Player/MyGuy.s"
	@echo "... src/Player/Player_Ball.o"
	@echo "... src/Player/Player_Ball.i"
	@echo "... src/Player/Player_Ball.s"
	@echo "... src/Player/Player_Bug.o"
	@echo "... src/Player/Player_Bug.i"
	@echo "... src/Player/Player_Bug.s"
	@echo "... src/Player/Player_Control.o"
	@echo "... src/Player/Player_Control.i"
	@echo "... src/Player/Player_Control.s"
	@echo "... src/QD3D/3DMF.o"
	@echo "... src/QD3D/3DMF.i"
	@echo "... src/QD3D/3DMF.s"
	@echo "... src/QD3D/3DMath.o"
	@echo "... src/QD3D/3DMath.i"
	@echo "... src/QD3D/3DMath.s"
	@echo "... src/QD3D/Camera.o"
	@echo "... src/QD3D/Camera.i"
	@echo "... src/QD3D/Camera.s"
	@echo "... src/QD3D/EnvironmentMap.o"
	@echo "... src/QD3D/EnvironmentMap.i"
	@echo "... src/QD3D/EnvironmentMap.s"
	@echo "... src/QD3D/FrustumCulling.o"
	@echo "... src/QD3D/FrustumCulling.i"
	@echo "... src/QD3D/FrustumCulling.s"
	@echo "... src/QD3D/Pick.o"
	@echo "... src/QD3D/Pick.i"
	@echo "... src/QD3D/Pick.s"
	@echo "... src/QD3D/QD3D_Geometry.o"
	@echo "... src/QD3D/QD3D_Geometry.i"
	@echo "... src/QD3D/QD3D_Geometry.s"
	@echo "... src/QD3D/QD3D_Support.o"
	@echo "... src/QD3D/QD3D_Support.i"
	@echo "... src/QD3D/QD3D_Support.s"
	@echo "... src/QD3D/Renderer.o"
	@echo "... src/QD3D/Renderer.i"
	@echo "... src/QD3D/Renderer.s"
	@echo "... src/QD3D/TextMesh.o"
	@echo "... src/QD3D/TextMesh.i"
	@echo "... src/QD3D/TextMesh.s"
	@echo "... src/QD3D/gles3_rhi.o"
	@echo "... src/QD3D/gles3_rhi.i"
	@echo "... src/QD3D/gles3_rhi.s"
	@echo "... src/Ride/DragonFly.o"
	@echo "... src/Ride/DragonFly.i"
	@echo "... src/Ride/DragonFly.s"
	@echo "... src/Ride/WaterBug.o"
	@echo "... src/Ride/WaterBug.i"
	@echo "... src/Ride/WaterBug.s"
	@echo "... src/Screens/AboutScreen.o"
	@echo "... src/Screens/AboutScreen.i"
	@echo "... src/Screens/AboutScreen.s"
	@echo "... src/Screens/BonusScreen.o"
	@echo "... src/Screens/BonusScreen.i"
	@echo "... src/Screens/BonusScreen.s"
	@echo "... src/Screens/FileSelect.o"
	@echo "... src/Screens/FileSelect.i"
	@echo "... src/Screens/FileSelect.s"
	@echo "... src/Screens/HighScores.o"
	@echo "... src/Screens/HighScores.i"
	@echo "... src/Screens/HighScores.s"
	@echo "... src/Screens/Infobar.o"
	@echo "... src/Screens/Infobar.i"
	@echo "... src/Screens/Infobar.s"
	@echo "... src/Screens/LevelIntro.o"
	@echo "... src/Screens/LevelIntro.i"
	@echo "... src/Screens/LevelIntro.s"
	@echo "... src/Screens/LevelSelect.o"
	@echo "... src/Screens/LevelSelect.i"
	@echo "... src/Screens/LevelSelect.s"
	@echo "... src/Screens/MainMenu.o"
	@echo "... src/Screens/MainMenu.i"
	@echo "... src/Screens/MainMenu.s"
	@echo "... src/Screens/MiscScreens.o"
	@echo "... src/Screens/MiscScreens.i"
	@echo "... src/Screens/MiscScreens.s"
	@echo "... src/Screens/ModelDebug.o"
	@echo "... src/Screens/ModelDebug.i"
	@echo "... src/Screens/ModelDebug.s"
	@echo "... src/Screens/SettingsScreen.o"
	@echo "... src/Screens/SettingsScreen.i"
	@echo "... src/Screens/SettingsScreen.s"
	@echo "... src/Screens/Title.o"
	@echo "... src/Screens/Title.i"
	@echo "... src/Screens/Title.s"
	@echo "... src/Screens/UIRoutines.o"
	@echo "... src/Screens/UIRoutines.i"
	@echo "... src/Screens/UIRoutines.s"
	@echo "... src/Screens/WinLose.o"
	@echo "... src/Screens/WinLose.i"
	@echo "... src/Screens/WinLose.s"
	@echo "... src/Skeleton/Bones.o"
	@echo "... src/Skeleton/Bones.i"
	@echo "... src/Skeleton/Bones.s"
	@echo "... src/Skeleton/SkeletonAnim.o"
	@echo "... src/Skeleton/SkeletonAnim.i"
	@echo "... src/Skeleton/SkeletonAnim.s"
	@echo "... src/Skeleton/SkeletonJoints.o"
	@echo "... src/Skeleton/SkeletonJoints.i"
	@echo "... src/Skeleton/SkeletonJoints.s"
	@echo "... src/Skeleton/SkeletonObj.o"
	@echo "... src/Skeleton/SkeletonObj.i"
	@echo "... src/Skeleton/SkeletonObj.s"
	@echo "... src/System/Collision.o"
	@echo "... src/System/Collision.i"
	@echo "... src/System/Collision.s"
	@echo "... src/System/File.o"
	@echo "... src/System/File.i"
	@echo "... src/System/File.s"
	@echo "... src/System/Input.o"
	@echo "... src/System/Input.i"
	@echo "... src/System/Input.s"
	@echo "... src/System/InputMacLinearMouse.o"
	@echo "... src/System/InputMacLinearMouse.i"
	@echo "... src/System/InputMacLinearMouse.s"
	@echo "... src/System/Main.o"
	@echo "... src/System/Main.i"
	@echo "... src/System/Main.s"
	@echo "... src/System/Misc.o"
	@echo "... src/System/Misc.i"
	@echo "... src/System/Misc.s"
	@echo "... src/System/MouseSmoothing.o"
	@echo "... src/System/MouseSmoothing.i"
	@echo "... src/System/MouseSmoothing.s"
	@echo "... src/System/Objects.o"
	@echo "... src/System/Objects.i"
	@echo "... src/System/Objects.s"
	@echo "... src/System/Objects2.o"
	@echo "... src/System/Objects2.i"
	@echo "... src/System/Objects2.s"
	@echo "... src/System/Pool.o"
	@echo "... src/System/Pool.i"
	@echo "... src/System/Pool.s"
	@echo "... src/System/SDLMaintenance.o"
	@echo "... src/System/SDLMaintenance.i"
	@echo "... src/System/SDLMaintenance.s"
	@echo "... src/System/Sound.o"
	@echo "... src/System/Sound.i"
	@echo "... src/System/Sound.s"
	@echo "... src/System/TGA.o"
	@echo "... src/System/TGA.i"
	@echo "... src/System/TGA.s"
	@echo "... src/System/Tween.o"
	@echo "... src/System/Tween.i"
	@echo "... src/System/Tween.s"
	@echo "... src/System/Window.o"
	@echo "... src/System/Window.i"
	@echo "... src/System/Window.s"
	@echo "... src/Terrain/Fences.o"
	@echo "... src/Terrain/Fences.i"
	@echo "... src/Terrain/Fences.s"
	@echo "... src/Terrain/SplineItems.o"
	@echo "... src/Terrain/SplineItems.i"
	@echo "... src/Terrain/SplineItems.s"
	@echo "... src/Terrain/Terrain.o"
	@echo "... src/Terrain/Terrain.i"
	@echo "... src/Terrain/Terrain.s"
	@echo "... src/Terrain/Terrain2.o"
	@echo "... src/Terrain/Terrain2.i"
	@echo "... src/Terrain/Terrain2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/runner/work/bugdom_wasm/bugdom_wasm/build-wasm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

